version: '3.8'

services:
  app:
    build: .
    image: ${ACR_HOST}/library-app:${TAG}
    container_name: library-app
    ports:
      - "8080:8080"
    volumes:
      - /path/to/prod/application.properties:/app/src/main/resources/application.properties:ro
    restart: unless-stopped
